In [21]:
import scipy.io as scio

In [22]:
data = scio.loadmat('SiftFlowDataset\GeoLabels\spatial_envelope_256x256_static_8outdoorcategories\coast_arnat59.mat')

In [23]:
data['S'].shape

(256, 256)

In [1]:
import os
import struct
import numpy as np

In [25]:
def load_mnist():
    with open(r'train-images-idx3-ubyte\train-images.idx3-ubyte', 'rb') as imgpath:
        magic, num, rows, cols = struct.unpack('>IIII',
                                               imgpath.read(16))
        images = np.fromfile(imgpath,
                             dtype=np.uint8).reshape(60000, 784)

    return images

In [26]:
data = load_mnist()

In [27]:
data[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [28]:
f = open(r'glove.840B.300d\glove.840B.300d.txt','r')
count = 0
data = np.array([])
for line in f:
    count += 1
    frags = line.strip().split(' ')[1:]
    data = np.append(data, np.array(frags))
    if count == 10:
        break

In [29]:
data = data.reshape(10, 300)

In [30]:
a = np.array([1, 2, 3, 4, 5, 6])
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
data = np.array([3, 2, 5, 1, 6, 4, 3])
data

array([3, 2, 5, 1, 6, 4, 3])

In [5]:
queries = np.zeros((1000, 35))
data = np.zeros((10000, 35))
dists = np.matrix(np.sum(np.square(queries), axis=1)).T + np.sum(np.square(data), axis=1)
print(dists.shape)
tmp = np.dot(queries, np.matrix(data).T)
tmp.shape

(1000, 10000)


(1000, 10000)